<?php
/**
 *
 * @var \Magento\Framework\View\Element\Template $block
 */
?>

<div class="custom-textarea-container" style="margin: 20px 0;">
    <form id="custom-textarea-form">
        <fieldset class="fieldset">
            <div class="field note">
                <label class="label" for="textarea_example">
                    <span><?php echo __('Textarea Attribute') ?></span>
                </label>
                <div class="control">
                    <textarea name="textarea_example" id="textarea_example" cols="15" rows="5" class="input-text"></textarea>
                </div>
            </div>
        </fieldset>
    </form>
</div>
