<?php
/** @var \Kalicr\BrandListing\Block\Widget\BrandSlider $block */
$brands = $block->getBrands();
$title = $block->getData('title');
?>

<?php if ($brands->count()): ?>
    <div class="brand-widget-container">
        <h2 class="brand-widget-title">
            <?= $title ? $block->escapeHtml($title) : __('We are authorized dealers of') ?>
        </h2>

        <div class="brand-slider-content" 
             data-mage-init='{
                "Kalicr_BrandListing/js/brand-slider": {
                    "slidesToShow": 5,
                    "autoplay": true
                }
             }'>
            <?php foreach ($brands as $brand): ?>
                <div class="brand-item">
                    <div class="brand-image-wrapper">
                        <img src="<?= $block->escapeUrl($block->getLogoUrl($brand->getLogo())) ?>" 
                             alt="<?= $block->escapeHtml($brand->getName()) ?>"
                             loading="lazy" />
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<style>
    .brand-slider-content {
                
        .brand-item {
            padding: 10px;
            text-align: center;
        }

        .brand-image-wrapper img {
            width: 150px;
            height: 150px;
            border-radius: 50%;
            overflow: hidden;
            border: 2px solid #eee;
            
            display: flex;
            align-items: center;
            justify-content: center;
            background: #fff;
            object-fit: cover;

        }
    }
</style>